"""fix users table

Revision ID: dc6ffc8207ea
Revises: 8f244854ffbd
Create Date: 2025-09-17 20:26:44.523789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc6ffc8207ea'
down_revision: Union[str, Sequence[str], None] = '8f244854ffbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_task_id'), table_name='users')
    op.drop_constraint(op.f('fk_user_task_id'), 'users', type_='foreignkey')
    op.drop_column('users', 'task_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_user_task_id'), 'users', 'tasks', ['task_id'], ['id'], deferrable=True)
    op.create_index(op.f('ix_users_task_id'), 'users', ['task_id'], unique=False)
    # ### end Alembic commands ###
